### ISSUE TITLE
menu links: having trouble adding baseurl between url and page urls

### ISSUE THREAD

**Issue by collinsinclair** [NCAR/jekyll-koru-test#7]
I'm working on [coral-viz](https://github.com/NCAR/coral-viz) and when `url` and `baseurl` are left as empty strings in `_config.yml`, my offline local server works as expected (yay!), *but* when I have the following set in `_config.yml`:
```
baseurl: "/coral-viz"
url: "https://ncar.github.io"
```
and in `mainmenu.yml`,
```
menu:
  - title: Home
    url: /coral-viz/
  - title: Discussion
    url: /coral-viz/pages/discussion/
```
etc, the links break when deployed to GitHub pages (boo!). Specifically, the `baseurl` does not seem to be added to menu links, so rather than, e.g., `https://ncar.github.io/coral-viz/pages/discussion`, the menu option **Discussion** points to `https://ncar.github.io/pages/discussion`. I'm sure I'm just using Jekyll incorrectly --- I'd be very thankful for any advice on how to get this issue fixed. Thanks!
